"""empty message

Revision ID: b32f8c05aa80
Revises: 4f0ff826ae6f
Create Date: 2023-04-30 15:53:58.738599

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b32f8c05aa80'
down_revision = '4f0ff826ae6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('follower_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('following_count', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('following_count')
        batch_op.drop_column('follower_count')

    # ### end Alembic commands ###
