"""empty message

Revision ID: ebff2005392d
Revises: b32f8c05aa80
Create Date: 2023-04-30 16:27:51.209587

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebff2005392d'
down_revision = 'b32f8c05aa80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.drop_column('user_token')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_token', sa.INTEGER(), nullable=False))
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
